### ISSUE TITLE
Example in zip doesn't work

### ISSUE THREAD

**Issue by nschepers** [marcostimm/Issuu-Gallery#1]
Hi

First of all: nice plugin.

I wanted to use it to make a nice pdf gallery integration into a website but when
I downloaded the zip, saved all files correctly and then open the index.html, 
there's no pdf showing.

I don't know whether I'm doing something wrong but the index.html example doesn't seem to work for me.

Thanks for helping !

**Comment by marcostimm** [comment]
It's work.
